# Generated by Django 5.0.4 on 2024-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammates',
            name='parentname',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
