# Generated by Django 5.0.4 on 2024-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammates_parentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammates',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
