# Generated by Django 5.0.4 on 2024-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammates_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='teammate_name',
            field=models.CharField(blank=True, default='Команда', max_length=255, null=True, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='teammates',
            name='rank',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
