# Generated by Django 5.0.4 on 2024-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_inventory_teammate_name_alter_teammates_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Пиротехника', 'pyrotechnics'), ('Привода', 'guns'), ('Продовольствие', 'food'), ('Расходники', 'consumables'), ('Реквизит', 'props'), ('Спальное снаряжение', 'sleepeng_gear'), ('Экипировка', 'equipment'), ('Прочее', 'other')], max_length=255, verbose_name='Категория'),
        ),
    ]
